baseURL = "https://abcdlsj.github.io"
defaultContentLanguage = "en"
hasCJKLanguage = true
languageCode = "en"
paginate = 5
theme = "hugo-theme-texify"
title = "Blog"

disqusShortname = ""
googleAnalytics = ""
pygmentsUseClasses = true

[author]
name = "abcdlsj"

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[[menu.main]]
  identifier = "post"
  name = "Post"
  url = "/"
  weight = 1
[[menu.main]]
  identifier = "archives"
  name = "Archives"
  url = "/post/"
  weight = 2
[[menu.main]]
  identifier = "about"
  name = "About"
  url = "/about/"
  weight = 3

[params]
  customCSS = []
  dateFormat = "2006-01-02"
  description = "Enjoy The Focus."
  enableFullRSS = true
  enableHanEmph = true
  enableMathjax = true
  favicon = "/favicon.ico"
  footnote = "Follow me on <a class=link href=https://github.com/abcdlsj>GitHub</a>"
  keywords = ["hugo", "latex", "theme"]
